[package]
name = "etg-server"
version = "0.1.0"
authors = ["serprex"]
edition = "2021"
description = "openEtG server"
license = "MIT"
repository = "https://github.com/serprex/openEtG"

[profile.dev]
opt-level = 1

[profile.release]
lto = "thin"

[dependencies]
base64 = "0.21"
bb8-postgres = { version = "0.8", features = ["with-serde_json-1"] }
brotli = "3"
etg = { version = "0.1", path = "../" }
form_urlencoded = "1"
futures = { version = "0.3", default-features = false, features = ["alloc"] }
fxhash = "0.2"
getrandom = "0.2"
hyper-tls = "0.5"
openssl = "0.10"
rand = "0.8"
rand_pcg = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
httpdate = "1"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
warp = { version = "0.3", default-features = false, features = ["websocket"] }