[package]
name = "etg-server"
version = "0.1.0"
authors = ["serprex"]
edition = "2021"
description = "openEtG server"
license = "MIT"
repository = "https://github.com/serprex/openEtG"

[profile.dev]
opt-level = 1

[dependencies]
async-compression = { version = "0.3", features = ["tokio", "gzip", "brotli"] }
base64 = "0.13"
bb8-postgres = { version = "0.7", features = ["with-serde_json-1"] }
etg = { version = "0.1", path = "../" }
futures = { version = "0.3", default-features = false, features = ["alloc"] }
form_urlencoded = "1.0"
fxhash = "0.2"
getrandom = "0.2"
hyper-tls = "0.5"
openssl = "0.10"
rand = { version = "0.8", default-features = false }
rand_pcg = { version = "0.3", default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
httpdate = "1"
tokio = { version = "1.0", features = ["full"] }
tokio-stream = "0.1"
warp = { version = "0.3", default-features = false, features = ["websocket"] }