[package]
name = "etg"
version = "0.1.0"
authors = ["serprex"]
edition = "2018"
description = "openEtG rust module"
license = "MIT"
repository = "https://github.com/serprex/openEtG"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
rand = { version = "0.8", default-features = false }
rand_pcg = { version = "0.3", default-features = false }
fxhash = "0.2"
arrayvec = { version = "0.5", default-features = false }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
console_error_panic_hook = { version = "0.1.6", optional = true }

[profile.release]
opt-level = "s"

[package.metadata.wasm-pack.profile.release]
wasm-opt = ['-Oz', '--enable-mutable-globals']

[[bin]]
name = "fuzz"

